### ISSUE TITLE
resolve the wheel poisoning

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [RedHatQE/webdriver_kaifuku#2]
the interaction of not having a python3 wheel and also not requiring a recent setuptools broke the build for many

**Comment by mshriver** [comment]
@RonnyPfannschmidt is this still an issue?

With #8 I'm dropping py2.7 support, and it looks like pypi has a py2/py3 whl at the moment.  With merging #8 deploy should only be building the py3 whl
