### ISSUE TITLE
add browser-option that allows to reenable keepalive

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [RedHatQE/webdriver_kaifuku#4]
@psav created images that support keepalive by using a local forward proxy, for those it should be possible to reenable keepalive

the proposal is to have a `proxy_supports_keepalive` key that kaifuku can discard in the passtrough

**Comment by quarckster** [comment]
Could we evaluate returning `keep-alive` with Selenium 4 release?

**Comment by RonnyPfannschmidt** [comment]
resolved with the changes
