### ISSUE TITLE
Deprecated config options not adapted for local chrome wedriver

### ISSUE THREAD

**Issue by dosas** [RedHatQE/webdriver_kaifuku#47]
When running `BrowserManager.from_conf()` for "local" chrome the deprecated settings option are [not adapted](https://github.com/RedHatQE/webdriver_kaifuku/blob/main/src/webdriver_kaifuku/__init__.py#L176) (like done for remote chrome).
Hence the additional args like _headless_, or _ignore-certificate-errors_ are not passed to the webdriver since they are filtered out [here](https://github.com/RedHatQE/webdriver_kaifuku/blob/main/src/webdriver_kaifuku/__init__.py#L75).

I could fix it locally by just removing the second half of the if clause:
```
if browser_name == "chrome"  # and webdriver_class == webdriver.Remote:
            webdriver_kwargs["options"] = cls._config_options_for_remote_chrome(browser_conf)
```

I suppose the same applies to [firefox](https://github.com/RedHatQE/webdriver_kaifuku/blob/main/src/webdriver_kaifuku/__init__.py#L176)

**Comment by RonnyPfannschmidt** [comment]
good catch, lets investigate fixing that

**Comment by dosas** [comment]
Sure, in order to reproduce:

```
from webdriver_kaifuku import BrowserManager


conf = {'webdriver': 'chrome', 'webdriver_options': {'desired_capabilities': {'browserName': 'chrome', 'chromeOptions': {'args': ['disable-web-security', 'ignore-certificate-errors', 'headless'], 'prefs': {'download.prompt_for_download': False}}}}}

BrowserManager.from_conf(conf).browser_factory.processed_browser_args()
```

Should return `{'options': <selenium.webdriver.chrome.options.Options at 0x7ff798c33210>}` instead of empty dict.

**Comment by RonnyPfannschmidt** [comment]
sounds like we have a starting point for a unittest :)
unfortunately i may not be able to spend time on this this week myself

**Comment by dosas** [comment]
I will see if I can create a PR but probably also not this week.

**Comment by dosas** [comment]
PR is done and ready for review.

**Comment by dosas** [comment]
Will there be a release for this change?

**Comment by RonnyPfannschmidt** [comment]
Thanks for the Ping, added to my agenda for tomorrow

**Comment by RonnyPfannschmidt** [comment]
finally triggered that release
